# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\loan_.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Loan_(object):
    def setupUi(self, Loan_):
        Loan_.setObjectName("Loan_")
        Loan_.resize(628, 394)
        Loan_.setMinimumSize(QtCore.QSize(628, 394))
        Loan_.setMaximumSize(QtCore.QSize(628, 394))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Loan_.setWindowIcon(icon)
        self.frame_2 = QtWidgets.QFrame(Loan_)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 681, 401))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(-50, 0, 231, 401))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../image/slide1.jpeg"))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(250, 20, 281, 61))
        self.label_5.setObjectName("label_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 628, 394))
        self.graphicsView.setMinimumSize(QtCore.QSize(628, 394))
        self.graphicsView.setMaximumSize(QtCore.QSize(628, 394))
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(240, 130, 91, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(240, 240, 91, 31))
        self.label_2.setObjectName("label_2")
        self.ConfirmButton = QtWidgets.QPushButton(self.frame_2)
        self.ConfirmButton.setGeometry(QtCore.QRect(300, 320, 61, 31))
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.CancelButton = QtWidgets.QPushButton(self.frame_2)
        self.CancelButton.setGeometry(QtCore.QRect(440, 320, 61, 31))
        self.CancelButton.setObjectName("CancelButton")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(240, 190, 91, 31))
        self.label_4.setObjectName("label_4")
        self.ID_num_2 = QtWidgets.QLabel(self.frame_2)
        self.ID_num_2.setGeometry(QtCore.QRect(370, 210, 181, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(14)
        self.ID_num_2.setFont(font)
        self.ID_num_2.setTextFormat(QtCore.Qt.RichText)
        self.ID_num_2.setObjectName("ID_num_2")
        self.StartdateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.StartdateEdit.setGeometry(QtCore.QRect(350, 190, 171, 22))
        self.StartdateEdit.setFrame(True)
        self.StartdateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2030, 1, 1), QtCore.QTime(23, 59, 59)))
        self.StartdateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.StartdateEdit.setCalendarPopup(True)
        self.StartdateEdit.setObjectName("StartdateEdit")
        self.EnddateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.EnddateEdit.setGeometry(QtCore.QRect(350, 240, 171, 22))
        self.EnddateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.EnddateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2030, 1, 1), QtCore.QTime(23, 59, 59)))
        self.EnddateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.EnddateEdit.setMaximumDate(QtCore.QDate(2030, 1, 1))
        self.EnddateEdit.setMinimumDate(QtCore.QDate(2020, 1, 1))
        self.EnddateEdit.setCalendarPopup(True)
        self.EnddateEdit.setObjectName("EnddateEdit")
        self.amountEdit = QtWidgets.QLineEdit(self.frame_2)
        self.amountEdit.setGeometry(QtCore.QRect(350, 139, 171, 21))
        self.amountEdit.setObjectName("amountEdit")
        self.retEdit = QtWidgets.QLabel(self.frame_2)
        self.retEdit.setGeometry(QtCore.QRect(350, 100, 171, 21))
        self.retEdit.setText("")
        self.retEdit.setObjectName("retEdit")
        self.graphicsView.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.ConfirmButton.raise_()
        self.CancelButton.raise_()
        self.label_4.raise_()
        self.ID_num_2.raise_()
        self.StartdateEdit.raise_()
        self.EnddateEdit.raise_()
        self.amountEdit.raise_()
        self.retEdit.raise_()

        self.retranslateUi(Loan_)
        QtCore.QMetaObject.connectSlotsByName(Loan_)
        Loan_.setTabOrder(self.amountEdit, self.StartdateEdit)
        Loan_.setTabOrder(self.StartdateEdit, self.EnddateEdit)
        Loan_.setTabOrder(self.EnddateEdit, self.ConfirmButton)
        Loan_.setTabOrder(self.ConfirmButton, self.CancelButton)
        Loan_.setTabOrder(self.CancelButton, self.graphicsView)

    def retranslateUi(self, Loan_):
        _translate = QtCore.QCoreApplication.translate
        Loan_.setWindowTitle(_translate("Loan_", "贷款"))
        self.label_5.setText(_translate("Loan_", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#184eff;\">-- 古 灵 阁 --</span></p></body></html>"))
        self.label.setText(_translate("Loan_", "<html><head/><body><p><span style=\" font-size:14pt;\">贷款金额：</span></p></body></html>"))
        self.label_2.setText(_translate("Loan_", "<html><head/><body><p><span style=\" font-size:14pt;\">还贷日期：</span></p></body></html>"))
        self.ConfirmButton.setText(_translate("Loan_", "确定"))
        self.CancelButton.setText(_translate("Loan_", "取消"))
        self.label_4.setText(_translate("Loan_", "<html><head/><body><p><span style=\" font-size:14pt;\">借贷日期：</span></p></body></html>"))
        self.ID_num_2.setText(_translate("Loan_", "<html><head/><body><p><br/></p></body></html>"))
        self.StartdateEdit.setDisplayFormat(_translate("Loan_", "yyyy-M-d"))
        self.EnddateEdit.setDisplayFormat(_translate("Loan_", "yyyy-M-d"))
