# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\open.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Open(object):
    def setupUi(self, Open):
        Open.setObjectName("Open")
        Open.resize(630, 399)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Open.setWindowIcon(icon)
        self.frame_2 = QtWidgets.QFrame(Open)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 681, 401))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(-50, 0, 691, 401))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../image/mainslide.jpg"))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(170, 10, 281, 61))
        self.label_5.setObjectName("label_5")
        self.ConfirmButton = QtWidgets.QPushButton(self.frame_2)
        self.ConfirmButton.setGeometry(QtCore.QRect(200, 340, 61, 31))
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.CancelButton = QtWidgets.QPushButton(self.frame_2)
        self.CancelButton.setGeometry(QtCore.QRect(340, 340, 61, 31))
        self.CancelButton.setObjectName("CancelButton")
        self.retEdit = QtWidgets.QLabel(self.frame_2)
        self.retEdit.setGeometry(QtCore.QRect(250, 60, 151, 21))
        self.retEdit.setText("")
        self.retEdit.setObjectName("retEdit")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView.setGeometry(QtCore.QRect(120, 0, 401, 401))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(160, 80, 81, 41))
        self.label.setObjectName("label")
        self.ID_num = QtWidgets.QLineEdit(self.frame_2)
        self.ID_num.setGeometry(QtCore.QRect(250, 90, 201, 20))
        self.ID_num.setObjectName("ID_num")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(170, 220, 61, 41))
        self.label_2.setObjectName("label_2")
        self.passEdit = QtWidgets.QLineEdit(self.frame_2)
        self.passEdit.setGeometry(QtCore.QRect(250, 140, 201, 20))
        self.passEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passEdit.setObjectName("passEdit")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(170, 180, 61, 41))
        self.label_4.setObjectName("label_4")
        self.nameEdit = QtWidgets.QLineEdit(self.frame_2)
        self.nameEdit.setGeometry(QtCore.QRect(250, 190, 201, 20))
        self.nameEdit.setObjectName("nameEdit")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(170, 260, 61, 41))
        self.label_6.setObjectName("label_6")
        self.phoneEdit = QtWidgets.QLineEdit(self.frame_2)
        self.phoneEdit.setGeometry(QtCore.QRect(250, 230, 201, 20))
        self.phoneEdit.setObjectName("phoneEdit")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(160, 130, 91, 41))
        self.label_7.setObjectName("label_7")
        self.addrEdit = QtWidgets.QLineEdit(self.frame_2)
        self.addrEdit.setGeometry(QtCore.QRect(250, 270, 201, 20))
        self.addrEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.addrEdit.setObjectName("addrEdit")
        self.label_3.raise_()
        self.graphicsView.raise_()
        self.label_5.raise_()
        self.ConfirmButton.raise_()
        self.CancelButton.raise_()
        self.retEdit.raise_()
        self.label.raise_()
        self.ID_num.raise_()
        self.label_2.raise_()
        self.passEdit.raise_()
        self.label_4.raise_()
        self.nameEdit.raise_()
        self.label_6.raise_()
        self.phoneEdit.raise_()
        self.label_7.raise_()
        self.addrEdit.raise_()

        self.retranslateUi(Open)
        QtCore.QMetaObject.connectSlotsByName(Open)
        Open.setTabOrder(self.ID_num, self.passEdit)
        Open.setTabOrder(self.passEdit, self.nameEdit)
        Open.setTabOrder(self.nameEdit, self.phoneEdit)
        Open.setTabOrder(self.phoneEdit, self.addrEdit)
        Open.setTabOrder(self.addrEdit, self.ConfirmButton)
        Open.setTabOrder(self.ConfirmButton, self.CancelButton)
        Open.setTabOrder(self.CancelButton, self.graphicsView)

    def retranslateUi(self, Open):
        _translate = QtCore.QCoreApplication.translate
        Open.setWindowTitle(_translate("Open", "填写个人信息"))
        self.label_5.setText(_translate("Open", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#184eff;\">-- 古 灵 阁 开 户--</span></p></body></html>"))
        self.ConfirmButton.setText(_translate("Open", "确定"))
        self.CancelButton.setText(_translate("Open", "取消"))
        self.label.setText(_translate("Open", "<html><head/><body><p><span style=\" font-size:14pt;\">身份证号</span></p></body></html>"))
        self.label_2.setText(_translate("Open", "<html><head/><body><p><span style=\" font-size:14pt;\">电 话 </span></p></body></html>"))
        self.label_4.setText(_translate("Open", "<html><head/><body><p><span style=\" font-size:14pt;\">姓 名 </span></p></body></html>"))
        self.label_6.setText(_translate("Open", "<html><head/><body><p><span style=\" font-size:14pt;\">地 址  </span></p></body></html>"))
        self.label_7.setText(_translate("Open", "<html><head/><body><p><span style=\" font-size:14pt;\">账户密码</span></p></body></html>"))
