# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\open_.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Open_(object):
    def setupUi(self, Open_):
        Open_.setObjectName("Open_")
        Open_.resize(630, 399)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Open_.setWindowIcon(icon)
        self.frame_2 = QtWidgets.QFrame(Open_)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 681, 401))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(-50, 0, 691, 401))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../image/mainslide.jpg"))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(170, 10, 281, 61))
        self.label_5.setObjectName("label_5")
        self.ConfirmButton = QtWidgets.QPushButton(self.frame_2)
        self.ConfirmButton.setGeometry(QtCore.QRect(220, 330, 61, 31))
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.CancelButton = QtWidgets.QPushButton(self.frame_2)
        self.CancelButton.setGeometry(QtCore.QRect(350, 330, 61, 31))
        self.CancelButton.setObjectName("CancelButton")
        self.retEdit = QtWidgets.QLabel(self.frame_2)
        self.retEdit.setGeometry(QtCore.QRect(250, 260, 151, 21))
        self.retEdit.setText("")
        self.retEdit.setObjectName("retEdit")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView.setGeometry(QtCore.QRect(120, 0, 401, 401))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(160, 70, 81, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(160, 220, 111, 41))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(170, 120, 71, 41))
        self.label_4.setObjectName("label_4")
        self.passEdit = QtWidgets.QLineEdit(self.frame_2)
        self.passEdit.setGeometry(QtCore.QRect(250, 230, 201, 20))
        self.passEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passEdit.setObjectName("passEdit")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(160, 270, 91, 41))
        self.label_6.setObjectName("label_6")
        self.confirmpassEdit = QtWidgets.QLineEdit(self.frame_2)
        self.confirmpassEdit.setGeometry(QtCore.QRect(250, 280, 201, 20))
        self.confirmpassEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpassEdit.setObjectName("confirmpassEdit")
        self.cardType = QtWidgets.QComboBox(self.frame_2)
        self.cardType.setGeometry(QtCore.QRect(250, 80, 201, 21))
        self.cardType.setObjectName("cardType")
        self.cardType.addItem("")
        self.cardType.addItem("")
        self.cardType.addItem("")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(160, 170, 111, 41))
        self.label_7.setObjectName("label_7")
        self.amountEdit = QtWidgets.QLineEdit(self.frame_2)
        self.amountEdit.setGeometry(QtCore.QRect(250, 180, 201, 20))
        self.amountEdit.setObjectName("amountEdit")
        self.cardId = QtWidgets.QLineEdit(self.frame_2)
        self.cardId.setGeometry(QtCore.QRect(250, 130, 201, 20))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        self.cardId.setFont(font)
        self.cardId.setReadOnly(True)
        self.cardId.setObjectName("cardId")
        self.label_3.raise_()
        self.graphicsView.raise_()
        self.label_5.raise_()
        self.ConfirmButton.raise_()
        self.CancelButton.raise_()
        self.retEdit.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.passEdit.raise_()
        self.label_6.raise_()
        self.confirmpassEdit.raise_()
        self.cardType.raise_()
        self.label_7.raise_()
        self.amountEdit.raise_()
        self.cardId.raise_()

        self.retranslateUi(Open_)
        QtCore.QMetaObject.connectSlotsByName(Open_)
        Open_.setTabOrder(self.cardType, self.amountEdit)
        Open_.setTabOrder(self.amountEdit, self.passEdit)
        Open_.setTabOrder(self.passEdit, self.confirmpassEdit)
        Open_.setTabOrder(self.confirmpassEdit, self.ConfirmButton)
        Open_.setTabOrder(self.ConfirmButton, self.CancelButton)
        Open_.setTabOrder(self.CancelButton, self.graphicsView)

    def retranslateUi(self, Open_):
        _translate = QtCore.QCoreApplication.translate
        Open_.setWindowTitle(_translate("Open_", "开户"))
        self.label_5.setText(_translate("Open_", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#184eff;\">-- 古 灵 阁 开 户--</span></p></body></html>"))
        self.ConfirmButton.setText(_translate("Open_", "确定"))
        self.CancelButton.setText(_translate("Open_", "取消"))
        self.label.setText(_translate("Open_", "<html><head/><body><p><span style=\" font-size:14pt;\">办卡类型</span></p></body></html>"))
        self.label_2.setText(_translate("Open_", "<html><head/><body><p><span style=\" font-size:14pt;\">设置密码</span></p></body></html>"))
        self.label_4.setText(_translate("Open_", "<html><head/><body><p><span style=\" font-size:14pt;\">新卡号： </span></p></body></html>"))
        self.label_6.setText(_translate("Open_", "<html><head/><body><p><span style=\" font-size:14pt;\">确认密码</span></p></body></html>"))
        self.cardType.setItemText(0, _translate("Open_", "招商银行一卡通"))
        self.cardType.setItemText(1, _translate("Open_", "工商银行牡丹卡"))
        self.cardType.setItemText(2, _translate("Open_", "邮政银行生肖卡"))
        self.label_7.setText(_translate("Open_", "<html><head/><body><p><span style=\" font-size:14pt;\">存入金额</span></p></body></html>"))
        self.amountEdit.setPlaceholderText(_translate("Open_", "最少10元哦"))
