# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\search.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Search(object):
    def setupUi(self, Search):
        Search.setObjectName("Search")
        Search.resize(628, 394)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Search.setWindowIcon(icon)
        self.frame_2 = QtWidgets.QFrame(Search)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 681, 401))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(-50, 0, 691, 401))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../image/mainslide.jpg"))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(40, 10, 181, 41))
        self.label_5.setObjectName("label_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 241, 381))
        self.graphicsView.setObjectName("graphicsView")
        self.cardEdit = QtWidgets.QLineEdit(self.frame_2)
        self.cardEdit.setGeometry(QtCore.QRect(70, 60, 161, 20))
        self.cardEdit.setObjectName("cardEdit")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 50, 51, 41))
        self.label.setObjectName("label")
        self.nameEdit = QtWidgets.QLineEdit(self.frame_2)
        self.nameEdit.setGeometry(QtCore.QRect(70, 100, 161, 20))
        self.nameEdit.setObjectName("nameEdit")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 51, 41))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 81, 41))
        self.label_4.setObjectName("label_4")
        self.idEdit = QtWidgets.QLineEdit(self.frame_2)
        self.idEdit.setGeometry(QtCore.QRect(110, 180, 121, 20))
        self.idEdit.setObjectName("idEdit")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 81, 41))
        self.label_6.setObjectName("label_6")
        self.dateEdit = QtWidgets.QLineEdit(self.frame_2)
        self.dateEdit.setGeometry(QtCore.QRect(110, 220, 121, 20))
        self.dateEdit.setObjectName("dateEdit")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 51, 41))
        self.label_7.setObjectName("label_7")
        self.phoneEdit = QtWidgets.QLineEdit(self.frame_2)
        self.phoneEdit.setGeometry(QtCore.QRect(70, 140, 161, 20))
        self.phoneEdit.setObjectName("phoneEdit")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 81, 41))
        self.label_8.setObjectName("label_8")
        self.amountEdit = QtWidgets.QLineEdit(self.frame_2)
        self.amountEdit.setGeometry(QtCore.QRect(110, 260, 121, 20))
        self.amountEdit.setObjectName("amountEdit")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(260, 10, 371, 191))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.SaveBox = QtWidgets.QCheckBox(self.frame_2)
        self.SaveBox.setGeometry(QtCore.QRect(30, 300, 81, 21))
        self.SaveBox.setStyleSheet("font: 14pt \"Agency FB\";")
        self.SaveBox.setChecked(True)
        self.SaveBox.setObjectName("SaveBox")
        self.WithdrawBox = QtWidgets.QCheckBox(self.frame_2)
        self.WithdrawBox.setGeometry(QtCore.QRect(130, 300, 81, 21))
        self.WithdrawBox.setStyleSheet("font: 14pt \"Agency FB\";")
        self.WithdrawBox.setChecked(True)
        self.WithdrawBox.setObjectName("WithdrawBox")
        self.TransBox = QtWidgets.QCheckBox(self.frame_2)
        self.TransBox.setGeometry(QtCore.QRect(30, 340, 81, 21))
        self.TransBox.setStyleSheet("font: 14pt \"Agency FB\";")
        self.TransBox.setChecked(True)
        self.TransBox.setObjectName("TransBox")
        self.LoanBox = QtWidgets.QCheckBox(self.frame_2)
        self.LoanBox.setGeometry(QtCore.QRect(130, 340, 81, 21))
        self.LoanBox.setStyleSheet("font: 14pt \"Agency FB\";")
        self.LoanBox.setChecked(True)
        self.LoanBox.setObjectName("LoanBox")
        self.infoTable = QtWidgets.QTableWidget(self.frame_2)
        self.infoTable.setGeometry(QtCore.QRect(260, 10, 371, 192))
        self.infoTable.setObjectName("infoTable")
        self.infoTable.setColumnCount(0)
        self.infoTable.setRowCount(0)
        self.infoTable.horizontalHeader().setHighlightSections(False)
        self.infoTable.verticalHeader().setVisible(False)
        self.tradeTable = QtWidgets.QTableWidget(self.frame_2)
        self.tradeTable.setGeometry(QtCore.QRect(260, 210, 371, 181))
        self.tradeTable.setObjectName("tradeTable")
        self.tradeTable.setColumnCount(0)
        self.tradeTable.setRowCount(0)
        self.tradeTable.horizontalHeader().setHighlightSections(False)
        self.tradeTable.verticalHeader().setVisible(False)
        self.label_3.raise_()
        self.graphicsView.raise_()
        self.label_5.raise_()
        self.cardEdit.raise_()
        self.label.raise_()
        self.nameEdit.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.idEdit.raise_()
        self.label_6.raise_()
        self.dateEdit.raise_()
        self.label_7.raise_()
        self.phoneEdit.raise_()
        self.label_8.raise_()
        self.amountEdit.raise_()
        self.graphicsView_2.raise_()
        self.SaveBox.raise_()
        self.WithdrawBox.raise_()
        self.TransBox.raise_()
        self.LoanBox.raise_()
        self.infoTable.raise_()
        self.tradeTable.raise_()

        self.retranslateUi(Search)
        QtCore.QMetaObject.connectSlotsByName(Search)
        Search.setTabOrder(self.cardEdit, self.nameEdit)
        Search.setTabOrder(self.nameEdit, self.phoneEdit)
        Search.setTabOrder(self.phoneEdit, self.idEdit)
        Search.setTabOrder(self.idEdit, self.dateEdit)
        Search.setTabOrder(self.dateEdit, self.amountEdit)
        Search.setTabOrder(self.amountEdit, self.SaveBox)
        Search.setTabOrder(self.SaveBox, self.WithdrawBox)
        Search.setTabOrder(self.WithdrawBox, self.TransBox)
        Search.setTabOrder(self.TransBox, self.LoanBox)
        Search.setTabOrder(self.LoanBox, self.graphicsView_2)
        Search.setTabOrder(self.graphicsView_2, self.graphicsView)
        Search.setTabOrder(self.graphicsView, self.infoTable)
        Search.setTabOrder(self.infoTable, self.tradeTable)

    def retranslateUi(self, Search):
        _translate = QtCore.QCoreApplication.translate
        Search.setWindowTitle(_translate("Search", "查询"))
        self.label_5.setText(_translate("Search", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#184eff;\">-- 古 灵 阁 --</span></p></body></html>"))
        self.label.setText(_translate("Search", "<html><head/><body><p><span style=\" font-size:14pt;\">卡号</span></p></body></html>"))
        self.label_2.setText(_translate("Search", "<html><head/><body><p><span style=\" font-size:14pt;\">姓名</span></p></body></html>"))
        self.label_4.setText(_translate("Search", "<html><head/><body><p><span style=\" font-size:14pt;\">交易日期</span></p></body></html>"))
        self.label_6.setText(_translate("Search", "<html><head/><body><p><span style=\" font-size:14pt;\">身份证号</span></p></body></html>"))
        self.label_7.setText(_translate("Search", "<html><head/><body><p><span style=\" font-size:14pt;\">电话</span></p></body></html>"))
        self.label_8.setText(_translate("Search", "<html><head/><body><p><span style=\" font-size:14pt;\">交易金额</span></p></body></html>"))
        self.SaveBox.setText(_translate("Search", "存款"))
        self.WithdrawBox.setText(_translate("Search", "取款"))
        self.TransBox.setText(_translate("Search", "转账"))
        self.LoanBox.setText(_translate("Search", "贷款"))
